domain:
  default:
    eureka: http://localhost:8888/eureka

server:
  port: 8082
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-status-check
          uri: lb://user-ws
          predicates:
            - Path=/users-ws/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${domain.default.eureka}
